// ══════════════════════════════════════════════
// LingoQuest – Content Bank
// 50+ items per track per game type
// ══════════════════════════════════════════════

// ─── WORD MATCH ──────────────────────────────
export const WORD_MATCH_CONTENT: Record<string, Array<{emoji: string, word: string, options: string[]}>> = {
  explorers: [
    { emoji: '🐱', word: 'Cat', options: ['Cat', 'Dog', 'Fish', 'Bird'] },
    { emoji: '🐶', word: 'Dog', options: ['Cat', 'Dog', 'Cow', 'Pig'] },
    { emoji: '🐟', word: 'Fish', options: ['Fish', 'Frog', 'Duck', 'Bee'] },
    { emoji: '🌈', word: 'Rainbow', options: ['Sun', 'Rainbow', 'Cloud', 'Star'] },
    { emoji: '🍎', word: 'Apple', options: ['Banana', 'Apple', 'Grape', 'Cherry'] },
    { emoji: '🌞', word: 'Sun', options: ['Moon', 'Star', 'Sun', 'Cloud'] },
    { emoji: '🏠', word: 'House', options: ['House', 'Tree', 'Car', 'Ball'] },
    { emoji: '🚗', word: 'Car', options: ['Bus', 'Bike', 'Car', 'Boat'] },
    { emoji: '🌺', word: 'Flower', options: ['Flower', 'Leaf', 'Tree', 'Grass'] },
    { emoji: '⭐', word: 'Star', options: ['Moon', 'Sun', 'Star', 'Cloud'] },
    { emoji: '🐸', word: 'Frog', options: ['Snake', 'Frog', 'Fish', 'Bird'] },
    { emoji: '🍌', word: 'Banana', options: ['Banana', 'Mango', 'Peach', 'Lemon'] },
    { emoji: '🐦', word: 'Bird', options: ['Ant', 'Bird', 'Bee', 'Bat'] },
    { emoji: '🌙', word: 'Moon', options: ['Star', 'Sun', 'Moon', 'Lamp'] },
    { emoji: '🎈', word: 'Balloon', options: ['Ball', 'Balloon', 'Kite', 'Hat'] },
    { emoji: '🐘', word: 'Elephant', options: ['Elephant', 'Giraffe', 'Lion', 'Bear'] },
    { emoji: '🍕', word: 'Pizza', options: ['Pizza', 'Cake', 'Bread', 'Soup'] },
    { emoji: '🎸', word: 'Guitar', options: ['Piano', 'Guitar', 'Drum', 'Flute'] },
    { emoji: '🚀', word: 'Rocket', options: ['Rocket', 'Plane', 'Boat', 'Train'] },
    { emoji: '🎂', word: 'Cake', options: ['Pie', 'Cake', 'Cookie', 'Candy'] },
    { emoji: '🐢', word: 'Turtle', options: ['Turtle', 'Snake', 'Lizard', 'Crab'] },
    { emoji: '🍦', word: 'Ice Cream', options: ['Ice Cream', 'Yogurt', 'Milk', 'Juice'] },
    { emoji: '🦊', word: 'Fox', options: ['Fox', 'Wolf', 'Dog', 'Bear'] },
    { emoji: '🎵', word: 'Music', options: ['Dance', 'Music', 'Song', 'Noise'] },
    { emoji: '🌳', word: 'Tree', options: ['Tree', 'Bush', 'Grass', 'Leaf'] },
    { emoji: '🐝', word: 'Bee', options: ['Bee', 'Fly', 'Ant', 'Bug'] },
    { emoji: '🧸', word: 'Bear', options: ['Bear', 'Doll', 'Ball', 'Toy'] },
    { emoji: '🍪', word: 'Cookie', options: ['Cookie', 'Cracker', 'Bread', 'Cake'] },
    { emoji: '👑', word: 'Crown', options: ['Hat', 'Crown', 'Ring', 'Cap'] },
    { emoji: '🦁', word: 'Lion', options: ['Tiger', 'Lion', 'Cat', 'Bear'] },
    { emoji: '🌻', word: 'Sunflower', options: ['Rose', 'Sunflower', 'Tulip', 'Daisy'] },
    { emoji: '🐙', word: 'Octopus', options: ['Octopus', 'Squid', 'Crab', 'Fish'] },
    { emoji: '🎪', word: 'Circus', options: ['Park', 'Circus', 'Zoo', 'School'] },
    { emoji: '🦋', word: 'Butterfly', options: ['Butterfly', 'Moth', 'Bird', 'Bee'] },
    { emoji: '🍉', word: 'Watermelon', options: ['Watermelon', 'Melon', 'Apple', 'Orange'] },
    { emoji: '🐧', word: 'Penguin', options: ['Duck', 'Penguin', 'Parrot', 'Owl'] },
    { emoji: '🎃', word: 'Pumpkin', options: ['Pumpkin', 'Tomato', 'Orange', 'Apple'] },
    { emoji: '🦷', word: 'Tooth', options: ['Tooth', 'Bone', 'Nail', 'Eye'] },
    { emoji: '🎒', word: 'Backpack', options: ['Backpack', 'Bag', 'Box', 'Basket'] },
    { emoji: '🌮', word: 'Taco', options: ['Taco', 'Burger', 'Pizza', 'Wrap'] },
  ],
  voyagers: [
    { emoji: '🍳', word: 'Kitchen', options: ['Bedroom', 'Kitchen', 'Garden', 'Library'] },
    { emoji: '🏔️', word: 'Mountain', options: ['Valley', 'Mountain', 'River', 'Desert'] },
    { emoji: '🔬', word: 'Science', options: ['Science', 'History', 'Music', 'Sports'] },
    { emoji: '🌊', word: 'Ocean', options: ['Lake', 'River', 'Ocean', 'Pond'] },
    { emoji: '🎭', word: 'Theater', options: ['Cinema', 'Theater', 'Museum', 'Library'] },
    { emoji: '🦁', word: 'Brave', options: ['Scared', 'Brave', 'Tired', 'Lazy'] },
    { emoji: '🎨', word: 'Creative', options: ['Creative', 'Boring', 'Simple', 'Quiet'] },
    { emoji: '🏰', word: 'Castle', options: ['Tower', 'Castle', 'Bridge', 'Temple'] },
    { emoji: '🧭', word: 'Adventure', options: ['Journey', 'Adventure', 'Vacation', 'Mission'] },
    { emoji: '🦋', word: 'Beautiful', options: ['Ugly', 'Beautiful', 'Small', 'Dark'] },
    { emoji: '🌋', word: 'Volcano', options: ['Volcano', 'Geyser', 'Canyon', 'Cliff'] },
    { emoji: '🏜️', word: 'Desert', options: ['Forest', 'Desert', 'Jungle', 'Swamp'] },
    { emoji: '🧲', word: 'Magnet', options: ['Battery', 'Magnet', 'Switch', 'Wire'] },
    { emoji: '🦅', word: 'Eagle', options: ['Parrot', 'Hawk', 'Eagle', 'Owl'] },
    { emoji: '🔭', word: 'Telescope', options: ['Telescope', 'Microscope', 'Camera', 'Binoculars'] },
    { emoji: '🧪', word: 'Experiment', options: ['Experiment', 'Exercise', 'Example', 'Experience'] },
    { emoji: '🏛️', word: 'Museum', options: ['Museum', 'Library', 'School', 'Church'] },
    { emoji: '🎯', word: 'Target', options: ['Goal', 'Target', 'Point', 'Score'] },
    { emoji: '🗿', word: 'Ancient', options: ['Modern', 'Ancient', 'New', 'Fresh'] },
    { emoji: '🌪️', word: 'Tornado', options: ['Hurricane', 'Tornado', 'Storm', 'Flood'] },
    { emoji: '🦈', word: 'Shark', options: ['Whale', 'Shark', 'Dolphin', 'Seal'] },
    { emoji: '🏹', word: 'Archer', options: ['Knight', 'Archer', 'Wizard', 'King'] },
    { emoji: '🎻', word: 'Violin', options: ['Guitar', 'Violin', 'Cello', 'Harp'] },
    { emoji: '🧬', word: 'DNA', options: ['RNA', 'DNA', 'Cell', 'Gene'] },
    { emoji: '🌐', word: 'Globe', options: ['Map', 'Globe', 'Atlas', 'World'] },
    { emoji: '⚡', word: 'Lightning', options: ['Thunder', 'Lightning', 'Storm', 'Rain'] },
    { emoji: '🦉', word: 'Wisdom', options: ['Knowledge', 'Wisdom', 'Smart', 'Clever'] },
    { emoji: '🎬', word: 'Director', options: ['Actor', 'Director', 'Writer', 'Singer'] },
    { emoji: '🧊', word: 'Glacier', options: ['Iceberg', 'Glacier', 'Snow', 'Frost'] },
    { emoji: '🦜', word: 'Parrot', options: ['Parrot', 'Pigeon', 'Robin', 'Crow'] },
    { emoji: '🏺', word: 'Pottery', options: ['Pottery', 'Painting', 'Sculpture', 'Drawing'] },
    { emoji: '🎪', word: 'Carnival', options: ['Festival', 'Carnival', 'Concert', 'Party'] },
    { emoji: '🧗', word: 'Climbing', options: ['Running', 'Climbing', 'Swimming', 'Flying'] },
    { emoji: '🌴', word: 'Tropical', options: ['Arctic', 'Tropical', 'Desert', 'Mountain'] },
    { emoji: '🎖️', word: 'Medal', options: ['Trophy', 'Medal', 'Prize', 'Award'] },
  ],
  masters: [
    { emoji: '🧊', word: 'Break the ice', options: ['Break the ice', 'Cold shoulder', 'On thin ice', 'Chill out'] },
    { emoji: '📖', word: 'Once upon a time', options: ['Long time ago', 'Once upon a time', 'In the beginning', 'Way back when'] },
    { emoji: '🌧️', word: 'Under the weather', options: ['Under the weather', 'Raining cats', 'Storm coming', 'Cloudy mind'] },
    { emoji: '💡', word: 'Bright idea', options: ['Smart move', 'Bright idea', 'Light bulb', 'Quick thought'] },
    { emoji: '🎯', word: 'Hit the nail', options: ['Hit the nail', 'Strike while hot', 'Hammer time', 'Right on target'] },
    { emoji: '🍰', word: 'Piece of cake', options: ['Easy peasy', 'Piece of cake', 'Sweet deal', 'Cherry on top'] },
    { emoji: '⏰', word: 'Against the clock', options: ['Running late', 'Against the clock', 'Time flies', 'Clock ticking'] },
    { emoji: '🎭', word: 'Break a leg', options: ['Good luck', 'Break a leg', 'Take a bow', 'Steal the show'] },
    { emoji: '🌍', word: 'Small world', options: ['Small world', 'Big picture', 'Wide open', 'Close call'] },
    { emoji: '🔥', word: 'On fire', options: ['Burning up', 'On fire', 'Hot stuff', 'Fired up'] },
    { emoji: '🐘', word: 'Elephant in the room', options: ['Elephant in the room', 'Big deal', 'Heavy topic', 'Large problem'] },
    { emoji: '🌈', word: 'Silver lining', options: ['Silver lining', 'Gold rush', 'Bright side', 'Light ahead'] },
    { emoji: '🐝', word: 'Busy as a bee', options: ['Busy as a bee', 'Fly like bird', 'Sting like wasp', 'Sweet as honey'] },
    { emoji: '🎵', word: 'Face the music', options: ['Play along', 'Face the music', 'Sound check', 'Tune in'] },
    { emoji: '🚀', word: 'Skyrocket', options: ['Blast off', 'Skyrocket', 'Take flight', 'Launch pad'] },
    { emoji: '🐺', word: 'Cry wolf', options: ['Cry wolf', 'Bark loud', 'Howl long', 'Run wild'] },
    { emoji: '💪', word: 'Bend over backwards', options: ['Bend over backwards', 'Stand tall', 'Push forward', 'Step aside'] },
    { emoji: '🎣', word: 'Hook line and sinker', options: ['Hook line and sinker', 'Cast the net', 'Reel it in', 'Go fishing'] },
    { emoji: '🦆', word: 'Sitting duck', options: ['Wild goose', 'Sitting duck', 'Ugly duckling', 'Lame duck'] },
    { emoji: '🌊', word: 'Go with the flow', options: ['Go with the flow', 'Swim upstream', 'Rock the boat', 'Make waves'] },
    { emoji: '🗝️', word: 'Under lock and key', options: ['Under lock and key', 'Open door', 'Hidden treasure', 'Secret passage'] },
    { emoji: '🎪', word: 'Run the show', options: ['Run the show', 'Watch the play', 'Join the act', 'Steal the scene'] },
    { emoji: '⚓', word: 'Learn the ropes', options: ['Learn the ropes', 'Tie the knot', 'Set sail', 'Drop anchor'] },
    { emoji: '🌙', word: 'Once in a blue moon', options: ['Once in a blue moon', 'Every other day', 'Now and then', 'Time after time'] },
    { emoji: '🃏', word: 'Wild card', options: ['Wild card', 'Ace up sleeve', 'Full house', 'Royal flush'] },
  ],
};

// ─── SPELLING ────────────────────────────────
export const SPELLING_CONTENT: Record<string, Array<{word: string, hint: string}>> = {
  explorers: [
    { word: 'CAT', hint: '🐱 A furry pet' }, { word: 'DOG', hint: '🐶 Best friend' },
    { word: 'SUN', hint: '🌞 Bright in sky' }, { word: 'BIG', hint: '📏 Not small' },
    { word: 'RED', hint: '🔴 A color' }, { word: 'HAT', hint: '🎩 On your head' },
    { word: 'CUP', hint: '☕ Drink from it' }, { word: 'BUS', hint: '🚌 Big vehicle' },
    { word: 'PEN', hint: '🖊️ Write with it' }, { word: 'BED', hint: '🛏️ Sleep in it' },
    { word: 'BOX', hint: '📦 Put things in it' }, { word: 'MAP', hint: '🗺️ Find your way' },
    { word: 'EGG', hint: '🥚 Comes from chicken' }, { word: 'JAM', hint: '🍓 Sweet on bread' },
    { word: 'ZIP', hint: '🤐 Close your jacket' }, { word: 'MOP', hint: '🧹 Clean the floor' },
    { word: 'NET', hint: '🥅 Catch things' }, { word: 'JUG', hint: '🫗 Pour water' },
    { word: 'FAN', hint: '🌀 Makes cool air' }, { word: 'RUG', hint: '🟫 On the floor' },
    { word: 'BAT', hint: '🦇 Flies at night' }, { word: 'COW', hint: '🐄 Gives milk' },
    { word: 'HEN', hint: '🐔 Lays eggs' }, { word: 'FOX', hint: '🦊 Clever animal' },
    { word: 'OWL', hint: '🦉 Night bird' }, { word: 'ANT', hint: '🐜 Tiny worker' },
    { word: 'PIE', hint: '🥧 Baked dessert' }, { word: 'JAR', hint: '🫙 Glass container' },
    { word: 'LOG', hint: '🪵 Part of tree' }, { word: 'WET', hint: '💧 Not dry' },
    { word: 'HOT', hint: '🔥 Very warm' }, { word: 'OLD', hint: '👴 Not young' },
    { word: 'NEW', hint: '✨ Not old' }, { word: 'SAD', hint: '😢 Not happy' },
    { word: 'FUN', hint: '🎉 Enjoyable' }, { word: 'RUN', hint: '🏃 Move fast' },
  ],
  voyagers: [
    { word: 'TIGER', hint: '🐅 Striped big cat' }, { word: 'OCEAN', hint: '🌊 Vast blue water' },
    { word: 'BRAVE', hint: '🦁 Not afraid' }, { word: 'DREAM', hint: '💭 While sleeping' },
    { word: 'LIGHT', hint: '💡 Opposite of dark' }, { word: 'WORLD', hint: '🌍 The whole planet' },
    { word: 'MUSIC', hint: '🎵 You listen to it' }, { word: 'GREEN', hint: '🟢 Color of grass' },
    { word: 'HAPPY', hint: '😊 Feeling good' }, { word: 'RIVER', hint: '🏞️ Flowing water' },
    { word: 'CLOUD', hint: '☁️ In the sky' }, { word: 'STONE', hint: '🪨 Hard rock' },
    { word: 'BEACH', hint: '🏖️ Sand and sea' }, { word: 'PAINT', hint: '🎨 Make art' },
    { word: 'CANDY', hint: '🍬 Sweet treat' }, { word: 'GHOST', hint: '👻 Scary spirit' },
    { word: 'CROWN', hint: '👑 King wears it' }, { word: 'PIZZA', hint: '🍕 Italian food' },
    { word: 'JUICE', hint: '🧃 Fruit drink' }, { word: 'PLANT', hint: '🌱 Grows in soil' },
    { word: 'MOUSE', hint: '🐭 Small rodent' }, { word: 'HORSE', hint: '🐴 You can ride it' },
    { word: 'SNAKE', hint: '🐍 No legs' }, { word: 'WHALE', hint: '🐋 Biggest animal' },
    { word: 'SMILE', hint: '😊 Show you are happy' }, { word: 'CHAIR', hint: '🪑 Sit on it' },
    { word: 'TRAIN', hint: '🚂 Rides on tracks' }, { word: 'BREAD', hint: '🍞 Make sandwich' },
    { word: 'QUEEN', hint: '👸 Female ruler' }, { word: 'MAGIC', hint: '✨ Like a wizard' },
    { word: 'DANCE', hint: '💃 Move to music' }, { word: 'STORM', hint: '⛈️ Thunder and rain' },
    { word: 'ROBOT', hint: '🤖 Machine person' }, { word: 'SPACE', hint: '🚀 Beyond Earth' },
    { word: 'NIGHT', hint: '🌙 When it is dark' }, { word: 'HEART', hint: '❤️ Love symbol' },
  ],
  masters: [
    { word: 'ADVENTURE', hint: '🗺️ Exciting journey' }, { word: 'BEAUTIFUL', hint: '🌸 Very pretty' },
    { word: 'KNOWLEDGE', hint: '📚 What you learn' }, { word: 'MYSTERIOUS', hint: '🔮 Unknown and strange' },
    { word: 'BRILLIANT', hint: '✨ Very smart' }, { word: 'CHALLENGE', hint: '🎯 A difficult task' },
    { word: 'DANGEROUS', hint: '⚠️ Could be harmful' }, { word: 'EXCELLENT', hint: '🏆 Outstanding' },
    { word: 'INVISIBLE', hint: '👻 Cannot be seen' }, { word: 'WONDERFUL', hint: '🌟 Amazing' },
    { word: 'EDUCATION', hint: '🎓 Learning process' }, { word: 'FANTASTIC', hint: '🤩 Incredibly good' },
    { word: 'GEOGRAPHY', hint: '🌍 Study of Earth' },  { word: 'HAPPINESS', hint: '😄 State of joy' },
    { word: 'IMAGINARY', hint: '💭 Not real' }, { word: 'JEALOUSY', hint: '💚 Envious feeling' },
    { word: 'LANDSCAPE', hint: '🏞️ Nature scenery' }, { word: 'MECHANISM', hint: '⚙️ How it works' },
    { word: 'NECESSARY', hint: '❗ Must have' }, { word: 'OPERATION', hint: '🏥 Medical procedure' },
    { word: 'PASSENGER', hint: '🚌 Person on a bus' }, { word: 'REBELLION', hint: '✊ Fight against' },
    { word: 'SATELLITE', hint: '🛰️ Orbits Earth' }, { word: 'TELESCOPE', hint: '🔭 See far away' },
    { word: 'UNIVERSAL', hint: '🌌 For everyone' }, { word: 'VOLUNTEER', hint: '🤝 Help for free' },
    { word: 'ELABORATE', hint: '📝 Very detailed' }, { word: 'FREQUENCY', hint: '📻 How often' },
    { word: 'GUARANTEE', hint: '✅ Promise it works' }, { word: 'HURRICANE', hint: '🌀 Powerful storm' },
  ],
};

// ─── SENTENCE BUILDER ────────────────────────
export const SENTENCE_CONTENT: Record<string, Array<{words: string[], correct: string}>> = {
  explorers: [
    { words: ['I', 'like', 'cats'], correct: 'I like cats' },
    { words: ['The', 'sun', 'is', 'big'], correct: 'The sun is big' },
    { words: ['She', 'has', 'a', 'dog'], correct: 'She has a dog' },
    { words: ['I', 'can', 'run', 'fast'], correct: 'I can run fast' },
    { words: ['The', 'bird', 'can', 'fly'], correct: 'The bird can fly' },
    { words: ['He', 'is', 'my', 'friend'], correct: 'He is my friend' },
    { words: ['We', 'play', 'at', 'school'], correct: 'We play at school' },
    { words: ['I', 'eat', 'an', 'apple'], correct: 'I eat an apple' },
    { words: ['The', 'cat', 'is', 'small'], correct: 'The cat is small' },
    { words: ['I', 'see', 'a', 'tree'], correct: 'I see a tree' },
    { words: ['She', 'likes', 'red', 'flowers'], correct: 'She likes red flowers' },
    { words: ['He', 'can', 'swim', 'well'], correct: 'He can swim well' },
    { words: ['We', 'love', 'ice', 'cream'], correct: 'We love ice cream' },
    { words: ['The', 'moon', 'is', 'bright'], correct: 'The moon is bright' },
    { words: ['I', 'have', 'two', 'hands'], correct: 'I have two hands' },
    { words: ['My', 'mom', 'is', 'nice'], correct: 'My mom is nice' },
    { words: ['The', 'fish', 'is', 'blue'], correct: 'The fish is blue' },
    { words: ['I', 'want', 'a', 'cookie'], correct: 'I want a cookie' },
    { words: ['She', 'reads', 'a', 'book'], correct: 'She reads a book' },
    { words: ['He', 'plays', 'with', 'balls'], correct: 'He plays with balls' },
  ],
  voyagers: [
    { words: ['The', 'children', 'are', 'playing', 'outside'], correct: 'The children are playing outside' },
    { words: ['She', 'always', 'reads', 'before', 'sleeping'], correct: 'She always reads before sleeping' },
    { words: ['We', 'went', 'to', 'the', 'beach'], correct: 'We went to the beach' },
    { words: ['My', 'mother', 'cooks', 'delicious', 'food'], correct: 'My mother cooks delicious food' },
    { words: ['They', 'will', 'visit', 'us', 'tomorrow'], correct: 'They will visit us tomorrow' },
    { words: ['The', 'movie', 'was', 'really', 'exciting'], correct: 'The movie was really exciting' },
    { words: ['I', 'have', 'been', 'studying', 'English'], correct: 'I have been studying English' },
    { words: ['He', 'does', 'not', 'like', 'spiders'], correct: 'He does not like spiders' },
    { words: ['The', 'teacher', 'explained', 'the', 'lesson'], correct: 'The teacher explained the lesson' },
    { words: ['We', 'should', 'help', 'each', 'other'], correct: 'We should help each other' },
    { words: ['She', 'is', 'learning', 'to', 'paint'], correct: 'She is learning to paint' },
    { words: ['They', 'traveled', 'around', 'the', 'world'], correct: 'They traveled around the world' },
    { words: ['The', 'dog', 'chased', 'the', 'cat'], correct: 'The dog chased the cat' },
    { words: ['I', 'forgot', 'my', 'homework', 'again'], correct: 'I forgot my homework again' },
    { words: ['She', 'danced', 'in', 'the', 'rain'], correct: 'She danced in the rain' },
    { words: ['We', 'built', 'a', 'sandcastle', 'together'], correct: 'We built a sandcastle together' },
    { words: ['The', 'birds', 'sing', 'every', 'morning'], correct: 'The birds sing every morning' },
    { words: ['He', 'wants', 'to', 'become', 'a', 'doctor'], correct: 'He wants to become a doctor' },
    { words: ['My', 'sister', 'is', 'taller', 'than', 'me'], correct: 'My sister is taller than me' },
    { words: ['The', 'stars', 'shine', 'at', 'night'], correct: 'The stars shine at night' },
  ],
  masters: [
    { words: ['Despite', 'the', 'rain', 'they', 'continued', 'walking'], correct: 'Despite the rain they continued walking' },
    { words: ['She', 'would', 'have', 'arrived', 'earlier'], correct: 'She would have arrived earlier' },
    { words: ['The', 'scientist', 'discovered', 'an', 'incredible', 'phenomenon'], correct: 'The scientist discovered an incredible phenomenon' },
    { words: ['Having', 'finished', 'the', 'exam', 'she', 'felt', 'relieved'], correct: 'Having finished the exam she felt relieved' },
    { words: ['The', 'more', 'you', 'practice', 'the', 'better'], correct: 'The more you practice the better' },
    { words: ['If', 'I', 'had', 'known', 'I', 'would', 'have', 'helped'], correct: 'If I had known I would have helped' },
    { words: ['Not', 'only', 'did', 'he', 'win', 'but', 'also', 'broke'], correct: 'Not only did he win but also broke' },
    { words: ['Neither', 'the', 'students', 'nor', 'teacher', 'agreed'], correct: 'Neither the students nor teacher agreed' },
    { words: ['Although', 'it', 'was', 'difficult', 'she', 'never', 'gave', 'up'], correct: 'Although it was difficult she never gave up' },
    { words: ['The', 'president', 'announced', 'a', 'new', 'policy'], correct: 'The president announced a new policy' },
    { words: ['By', 'the', 'time', 'we', 'arrived', 'it', 'had', 'started'], correct: 'By the time we arrived it had started' },
    { words: ['She', 'suggested', 'that', 'we', 'leave', 'immediately'], correct: 'She suggested that we leave immediately' },
    { words: ['The', 'documentary', 'explored', 'ancient', 'civilizations'], correct: 'The documentary explored ancient civilizations' },
    { words: ['Had', 'they', 'prepared', 'better', 'they', 'would', 'have', 'succeeded'], correct: 'Had they prepared better they would have succeeded' },
    { words: ['Regardless', 'of', 'the', 'outcome', 'we', 'learned', 'a', 'lot'], correct: 'Regardless of the outcome we learned a lot' },
  ],
};

// ─── LISTENING ───────────────────────────────
export const LISTENING_CONTENT: Record<string, Array<{word: string, options: string[]}>> = {
  explorers: [
    { word: 'Hello', options: ['Hello', 'Yellow', 'Jello', 'Fellow'] },
    { word: 'Apple', options: ['Apple', 'Ape', 'Able', 'April'] },
    { word: 'Water', options: ['Winter', 'Water', 'Waiter', 'Weather'] },
    { word: 'Happy', options: ['Happy', 'Hippy', 'Hoppy', 'Handy'] },
    { word: 'Green', options: ['Grain', 'Green', 'Great', 'Greet'] },
    { word: 'House', options: ['Horse', 'House', 'Mouse', 'Hose'] },
    { word: 'Blue', options: ['Blow', 'Blue', 'Blur', 'Blew'] },
    { word: 'Milk', options: ['Milk', 'Silk', 'Mill', 'Melt'] },
    { word: 'Book', options: ['Look', 'Book', 'Cook', 'Hook'] },
    { word: 'Ball', options: ['Bell', 'Bill', 'Ball', 'Bull'] },
    { word: 'Rain', options: ['Rain', 'Run', 'Ruin', 'Ran'] },
    { word: 'Jump', options: ['Dump', 'Bump', 'Jump', 'Pump'] },
    { word: 'Tree', options: ['Free', 'Tree', 'Three', 'Thee'] },
    { word: 'Fish', options: ['Dish', 'Fish', 'Wish', 'Fist'] },
    { word: 'Door', options: ['Door', 'Deer', 'Dear', 'Dare'] },
    { word: 'Snow', options: ['Show', 'Snow', 'Slow', 'Know'] },
    { word: 'Cake', options: ['Cape', 'Cake', 'Lake', 'Make'] },
    { word: 'Sing', options: ['Sing', 'Ring', 'King', 'Wing'] },
    { word: 'Play', options: ['Pray', 'Play', 'Clay', 'Slay'] },
    { word: 'Dark', options: ['Bark', 'Dark', 'Park', 'Mark'] },
  ],
  voyagers: [
    { word: 'Beautiful', options: ['Beautiful', 'Bountiful', 'Botanical', 'Butterfly'] },
    { word: 'Chocolate', options: ['Challenge', 'Chocolate', 'Champion', 'Character'] },
    { word: 'Important', options: ['Impatient', 'Impossible', 'Important', 'Immediate'] },
    { word: 'Vegetable', options: ['Vegetable', 'Variable', 'Valuable', 'Vulnerable'] },
    { word: 'Wonderful', options: ['Wanderful', 'Wonderful', 'Waterfall', 'Worthwhile'] },
    { word: 'Different', options: ['Difficult', 'Different', 'Diligent', 'Diplomat'] },
    { word: 'Dangerous', options: ['Dangerous', 'Generous', 'Glamorous', 'Delicious'] },
    { word: 'Furniture', options: ['Fortune', 'Furniture', 'Further', 'Feature'] },
    { word: 'Celebrate', options: ['Celebrate', 'Calibrate', 'Calculate', 'Cultivate'] },
    { word: 'Butterfly', options: ['Butterfly', 'Buttercup', 'Beautiful', 'Battleship'] },
    { word: 'Education', options: ['Elevation', 'Education', 'Equation', 'Evolution'] },
    { word: 'Invisible', options: ['Invisible', 'Invincible', 'Incredible', 'Inaudible'] },
    { word: 'Kangaroo', options: ['Kangaroo', 'Cockatoo', 'Caribou', 'Koala'] },
    { word: 'Dinosaur', options: ['Dinosaur', 'Dilemma', 'Discover', 'Diamond'] },
    { word: 'Crocodile', options: ['Crocodile', 'Chronicle', 'Character', 'Chocolate'] },
    { word: 'Ambulance', options: ['Ambulance', 'Abundance', 'Appearance', 'Appliance'] },
    { word: 'Telescope', options: ['Telephone', 'Telescope', 'Television', 'Telegraph'] },
    { word: 'Lemonade', options: ['Lemonade', 'Limousine', 'Landscape', 'Longitude'] },
    { word: 'Porcupine', options: ['Porcupine', 'Porcelain', 'Populating', 'Producing'] },
    { word: 'Trampoline', options: ['Trampoline', 'Tambourine', 'Trampling', 'Traveling'] },
  ],
  masters: [
    { word: 'Phenomenon', options: ['Phenomenon', 'Philosophy', 'Philanthropy', 'Photography'] },
    { word: 'Consequences', options: ['Consciousness', 'Consequences', 'Confidential', 'Contemporary'] },
    { word: 'Sophisticated', options: ['Sophisticated', 'Sympathetic', 'Supplementary', 'Surveillance'] },
    { word: 'Extraordinary', options: ['Extravagant', 'Extraordinary', 'Experimental', 'Exaggerated'] },
    { word: 'Refrigerator', options: ['Refrigerator', 'Reverberate', 'Rehabilitate', 'Recommendation'] },
    { word: 'Approximately', options: ['Appropriately', 'Approximately', 'Appreciatively', 'Authentically'] },
    { word: 'Pronunciation', options: ['Proclamation', 'Pronunciation', 'Predominant', 'Professional'] },
    { word: 'Encyclopedia', options: ['Encyclopedia', 'Enthusiastic', 'Environmental', 'Entrepreneurial'] },
    { word: 'Architecture', options: ['Architecture', 'Archaeology', 'Aristocracy', 'Articulation'] },
    { word: 'Civilization', options: ['Civilization', 'Celebration', 'Collaboration', 'Communication'] },
    { word: 'Determination', options: ['Determination', 'Deterioration', 'Documentation', 'Denomination'] },
    { word: 'Exaggeration', options: ['Exaggeration', 'Examination', 'Exploitation', 'Expectation'] },
    { word: 'Hallucination', options: ['Hallucination', 'Hesitation', 'Humiliation', 'Hibernation'] },
    { word: 'Interpretation', options: ['Interpretation', 'Investigation', 'Improvisation', 'Implementation'] },
    { word: 'Mathematician', options: ['Mathematician', 'Metropolitan', 'Manipulation', 'Manifestation'] },
    { word: 'Onomatopoeia', options: ['Onomatopoeia', 'Opportunity', 'Optimization', 'Organization'] },
    { word: 'Perpendicular', options: ['Perpendicular', 'Pharmaceutical', 'Participating', 'Procrastinate'] },
    { word: 'Questionnaire', options: ['Questionnaire', 'Quarantine', 'Quintessential', 'Qualification'] },
    { word: 'Rehabilitation', options: ['Rehabilitation', 'Representation', 'Recommendation', 'Refrigeration'] },
    { word: 'Simultaneously', options: ['Simultaneously', 'Systematically', 'Spontaneously', 'Substantially'] },
  ],
};