// ══════════════════════════════════════════════
// LingoQuest – Content Bank with Hebrew
// ══════════════════════════════════════════════

export const WORD_MATCH_CONTENT: Record<string, Array<{emoji: string, word: string, wordHe: string, options: string[]}>> = {
  explorers: [
    { emoji: '🐱', word: 'Cat', wordHe: 'חתול', options: ['Cat', 'Dog', 'Fish', 'Bird'] },
    { emoji: '🐶', word: 'Dog', wordHe: 'כלב', options: ['Cat', 'Dog', 'Cow', 'Pig'] },
    { emoji: '🐟', word: 'Fish', wordHe: 'דג', options: ['Fish', 'Frog', 'Duck', 'Bee'] },
    { emoji: '🌈', word: 'Rainbow', wordHe: 'קשת', options: ['Sun', 'Rainbow', 'Cloud', 'Star'] },
    { emoji: '🍎', word: 'Apple', wordHe: 'תפוח', options: ['Banana', 'Apple', 'Grape', 'Cherry'] },
    { emoji: '🌞', word: 'Sun', wordHe: 'שמש', options: ['Moon', 'Star', 'Sun', 'Cloud'] },
    { emoji: '🏠', word: 'House', wordHe: 'בית', options: ['House', 'Tree', 'Car', 'Ball'] },
    { emoji: '🚗', word: 'Car', wordHe: 'מכונית', options: ['Bus', 'Bike', 'Car', 'Boat'] },
    { emoji: '🌺', word: 'Flower', wordHe: 'פרח', options: ['Flower', 'Leaf', 'Tree', 'Grass'] },
    { emoji: '⭐', word: 'Star', wordHe: 'כוכב', options: ['Moon', 'Sun', 'Star', 'Cloud'] },
    { emoji: '🐸', word: 'Frog', wordHe: 'צפרדע', options: ['Snake', 'Frog', 'Fish', 'Bird'] },
    { emoji: '🍌', word: 'Banana', wordHe: 'בננה', options: ['Banana', 'Mango', 'Peach', 'Lemon'] },
    { emoji: '🐦', word: 'Bird', wordHe: 'ציפור', options: ['Ant', 'Bird', 'Bee', 'Bat'] },
    { emoji: '🌙', word: 'Moon', wordHe: 'ירח', options: ['Star', 'Sun', 'Moon', 'Lamp'] },
    { emoji: '🎈', word: 'Balloon', wordHe: 'בלון', options: ['Ball', 'Balloon', 'Kite', 'Hat'] },
    { emoji: '🐘', word: 'Elephant', wordHe: 'פיל', options: ['Elephant', 'Giraffe', 'Lion', 'Bear'] },
    { emoji: '🍕', word: 'Pizza', wordHe: 'פיצה', options: ['Pizza', 'Cake', 'Bread', 'Soup'] },
    { emoji: '🚀', word: 'Rocket', wordHe: 'טיל', options: ['Rocket', 'Plane', 'Boat', 'Train'] },
    { emoji: '🎂', word: 'Cake', wordHe: 'עוגה', options: ['Pie', 'Cake', 'Cookie', 'Candy'] },
    { emoji: '🐢', word: 'Turtle', wordHe: 'צב', options: ['Turtle', 'Snake', 'Lizard', 'Crab'] },
    { emoji: '🍦', word: 'Ice Cream', wordHe: 'גלידה', options: ['Ice Cream', 'Yogurt', 'Milk', 'Juice'] },
    { emoji: '🦊', word: 'Fox', wordHe: 'שועל', options: ['Fox', 'Wolf', 'Dog', 'Bear'] },
    { emoji: '🌳', word: 'Tree', wordHe: 'עץ', options: ['Tree', 'Bush', 'Grass', 'Leaf'] },
    { emoji: '🐝', word: 'Bee', wordHe: 'דבורה', options: ['Bee', 'Fly', 'Ant', 'Bug'] },
    { emoji: '🍪', word: 'Cookie', wordHe: 'עוגייה', options: ['Cookie', 'Cracker', 'Bread', 'Cake'] },
    { emoji: '👑', word: 'Crown', wordHe: 'כתר', options: ['Hat', 'Crown', 'Ring', 'Cap'] },
    { emoji: '🦁', word: 'Lion', wordHe: 'אריה', options: ['Tiger', 'Lion', 'Cat', 'Bear'] },
    { emoji: '🐙', word: 'Octopus', wordHe: 'תמנון', options: ['Octopus', 'Squid', 'Crab', 'Fish'] },
    { emoji: '🦋', word: 'Butterfly', wordHe: 'פרפר', options: ['Butterfly', 'Moth', 'Bird', 'Bee'] },
    { emoji: '🍉', word: 'Watermelon', wordHe: 'אבטיח', options: ['Watermelon', 'Melon', 'Apple', 'Orange'] },
    { emoji: '🐧', word: 'Penguin', wordHe: 'פינגווין', options: ['Duck', 'Penguin', 'Parrot', 'Owl'] },
    { emoji: '🎒', word: 'Backpack', wordHe: 'תיק גב', options: ['Backpack', 'Bag', 'Box', 'Basket'] },
    { emoji: '🌮', word: 'Taco', wordHe: 'טאקו', options: ['Taco', 'Burger', 'Pizza', 'Wrap'] },
    { emoji: '🐷', word: 'Pig', wordHe: 'חזיר', options: ['Pig', 'Dog', 'Cat', 'Cow'] },
    { emoji: '🐴', word: 'Horse', wordHe: 'סוס', options: ['Horse', 'Donkey', 'Cow', 'Goat'] },
    { emoji: '🦆', word: 'Duck', wordHe: 'ברווז', options: ['Duck', 'Chicken', 'Bird', 'Goose'] },
    { emoji: '🐑', word: 'Sheep', wordHe: 'כבשה', options: ['Sheep', 'Goat', 'Dog', 'Cat'] },
    { emoji: '🐄', word: 'Cow', wordHe: 'פרה', options: ['Cow', 'Horse', 'Pig', 'Bull'] },
    { emoji: '🍇', word: 'Grapes', wordHe: 'ענבים', options: ['Grapes', 'Cherry', 'Berry', 'Plum'] },
    { emoji: '🍊', word: 'Orange', wordHe: 'תפוז', options: ['Orange', 'Lemon', 'Apple', 'Peach'] },
    { emoji: '🍓', word: 'Strawberry', wordHe: 'תות', options: ['Strawberry', 'Cherry', 'Berry', 'Grape'] },
    { emoji: '🥕', word: 'Carrot', wordHe: 'גזר', options: ['Carrot', 'Potato', 'Onion', 'Corn'] },
    { emoji: '🌽', word: 'Corn', wordHe: 'תירס', options: ['Corn', 'Pea', 'Bean', 'Rice'] },
    { emoji: '🧀', word: 'Cheese', wordHe: 'גבינה', options: ['Cheese', 'Butter', 'Milk', 'Cream'] },
    { emoji: '🍞', word: 'Bread', wordHe: 'לחם', options: ['Bread', 'Cake', 'Cookie', 'Toast'] },
    { emoji: '🥛', word: 'Milk', wordHe: 'חלב', options: ['Milk', 'Water', 'Juice', 'Tea'] },
    { emoji: '☂️', word: 'Umbrella', wordHe: 'מטרייה', options: ['Umbrella', 'Hat', 'Coat', 'Bag'] },
    { emoji: '👟', word: 'Shoes', wordHe: 'נעליים', options: ['Shoes', 'Socks', 'Boots', 'Pants'] },
    { emoji: '👕', word: 'Shirt', wordHe: 'חולצה', options: ['Shirt', 'Pants', 'Dress', 'Hat'] },
    { emoji: '🎩', word: 'Hat', wordHe: 'כובע', options: ['Hat', 'Cap', 'Scarf', 'Glove'] },
    { emoji: '✏️', word: 'Pencil', wordHe: 'עיפרון', options: ['Pencil', 'Pen', 'Brush', 'Ruler'] },
    { emoji: '📚', word: 'Book', wordHe: 'ספר', options: ['Book', 'Paper', 'Letter', 'Card'] },
    { emoji: '⚽', word: 'Ball', wordHe: 'כדור', options: ['Ball', 'Bat', 'Ring', 'Wheel'] },
    { emoji: '🎸', word: 'Guitar', wordHe: 'גיטרה', options: ['Guitar', 'Piano', 'Drum', 'Flute'] },
    { emoji: '🕐', word: 'Clock', wordHe: 'שעון', options: ['Clock', 'Watch', 'Bell', 'Timer'] },
    { emoji: '🪟', word: 'Window', wordHe: 'חלון', options: ['Window', 'Door', 'Wall', 'Floor'] },
    { emoji: '🚪', word: 'Door', wordHe: 'דלת', options: ['Door', 'Gate', 'Window', 'Wall'] },
    { emoji: '🛏️', word: 'Bed', wordHe: 'מיטה', options: ['Bed', 'Chair', 'Table', 'Sofa'] },
    { emoji: '🪑', word: 'Chair', wordHe: 'כיסא', options: ['Chair', 'Bench', 'Stool', 'Bed'] },
    { emoji: '🐊', word: 'Crocodile', wordHe: 'תנין', options: ['Crocodile', 'Lizard', 'Snake', 'Turtle'] },
    { emoji: '🦒', word: 'Giraffe', wordHe: 'ג\'ירפה', options: ['Giraffe', 'Elephant', 'Horse', 'Deer'] },
    { emoji: '🐬', word: 'Dolphin', wordHe: 'דולפין', options: ['Dolphin', 'Whale', 'Shark', 'Fish'] },
    { emoji: '🦅', word: 'Eagle', wordHe: 'נשר', options: ['Eagle', 'Hawk', 'Owl', 'Parrot'] },
  ],
  voyagers: [
    { emoji: '🍳', word: 'Kitchen', wordHe: 'מטבח', options: ['Bedroom', 'Kitchen', 'Garden', 'Library'] },
    { emoji: '🏔️', word: 'Mountain', wordHe: 'הר', options: ['Valley', 'Mountain', 'River', 'Desert'] },
    { emoji: '🔬', word: 'Science', wordHe: 'מדע', options: ['Science', 'History', 'Music', 'Sports'] },
    { emoji: '🌊', word: 'Ocean', wordHe: 'אוקיינוס', options: ['Lake', 'River', 'Ocean', 'Pond'] },
    { emoji: '🎭', word: 'Theater', wordHe: 'תיאטרון', options: ['Cinema', 'Theater', 'Museum', 'Library'] },
    { emoji: '🦁', word: 'Brave', wordHe: 'אמיץ', options: ['Scared', 'Brave', 'Tired', 'Lazy'] },
    { emoji: '🎨', word: 'Creative', wordHe: 'יצירתי', options: ['Creative', 'Boring', 'Simple', 'Quiet'] },
    { emoji: '🏰', word: 'Castle', wordHe: 'טירה', options: ['Tower', 'Castle', 'Bridge', 'Temple'] },
    { emoji: '🧭', word: 'Adventure', wordHe: 'הרפתקה', options: ['Journey', 'Adventure', 'Vacation', 'Mission'] },
    { emoji: '🦋', word: 'Beautiful', wordHe: 'יפה', options: ['Ugly', 'Beautiful', 'Small', 'Dark'] },
    { emoji: '🌋', word: 'Volcano', wordHe: 'הר געש', options: ['Volcano', 'Geyser', 'Canyon', 'Cliff'] },
    { emoji: '🏜️', word: 'Desert', wordHe: 'מדבר', options: ['Forest', 'Desert', 'Jungle', 'Swamp'] },
    { emoji: '🦅', word: 'Eagle', wordHe: 'נשר', options: ['Parrot', 'Hawk', 'Eagle', 'Owl'] },
    { emoji: '🔭', word: 'Telescope', wordHe: 'טלסקופ', options: ['Telescope', 'Microscope', 'Camera', 'Binoculars'] },
    { emoji: '🏛️', word: 'Museum', wordHe: 'מוזיאון', options: ['Museum', 'Library', 'School', 'Church'] },
    { emoji: '🌪️', word: 'Tornado', wordHe: 'טורנדו', options: ['Hurricane', 'Tornado', 'Storm', 'Flood'] },
    { emoji: '🦈', word: 'Shark', wordHe: 'כריש', options: ['Whale', 'Shark', 'Dolphin', 'Seal'] },
    { emoji: '🎻', word: 'Violin', wordHe: 'כינור', options: ['Guitar', 'Violin', 'Cello', 'Harp'] },
    { emoji: '⚡', word: 'Lightning', wordHe: 'ברק', options: ['Thunder', 'Lightning', 'Storm', 'Rain'] },
    { emoji: '🦉', word: 'Wisdom', wordHe: 'חוכמה', options: ['Knowledge', 'Wisdom', 'Smart', 'Clever'] },
    { emoji: '🧊', word: 'Glacier', wordHe: 'קרחון', options: ['Iceberg', 'Glacier', 'Snow', 'Frost'] },
    { emoji: '🦜', word: 'Parrot', wordHe: 'תוכי', options: ['Parrot', 'Pigeon', 'Robin', 'Crow'] },
    { emoji: '🌴', word: 'Tropical', wordHe: 'טרופי', options: ['Arctic', 'Tropical', 'Desert', 'Mountain'] },
    { emoji: '🎖️', word: 'Medal', wordHe: 'מדליה', options: ['Trophy', 'Medal', 'Prize', 'Award'] },
    { emoji: '🏖️', word: 'Beach', wordHe: 'חוף', options: ['Beach', 'Pool', 'Lake', 'River'] },
    { emoji: '🎪', word: 'Circus', wordHe: 'קרקס', options: ['Circus', 'Zoo', 'Park', 'Stage'] },
    { emoji: '🧲', word: 'Magnet', wordHe: 'מגנט', options: ['Magnet', 'Metal', 'Stone', 'Wire'] },
    { emoji: '🏆', word: 'Champion', wordHe: 'אלוף', options: ['Winner', 'Champion', 'Leader', 'Hero'] },
    { emoji: '🎯', word: 'Target', wordHe: 'מטרה', options: ['Target', 'Goal', 'Point', 'Mark'] },
    { emoji: '🧪', word: 'Experiment', wordHe: 'ניסוי', options: ['Experiment', 'Research', 'Study', 'Test'] },
    { emoji: '🗺️', word: 'Geography', wordHe: 'גיאוגרפיה', options: ['History', 'Geography', 'Biology', 'Math'] },
    { emoji: '🏗️', word: 'Construction', wordHe: 'בנייה', options: ['Construction', 'Destruction', 'Creation', 'Formation'] },
    { emoji: '🎬', word: 'Director', wordHe: 'במאי', options: ['Actor', 'Director', 'Writer', 'Producer'] },
    { emoji: '🧑‍🍳', word: 'Chef', wordHe: 'שף', options: ['Chef', 'Waiter', 'Baker', 'Cook'] },
    { emoji: '🧑‍🚀', word: 'Astronaut', wordHe: 'אסטרונאוט', options: ['Pilot', 'Astronaut', 'Captain', 'Engineer'] },
    { emoji: '🧑‍🏫', word: 'Professor', wordHe: 'פרופסור', options: ['Student', 'Professor', 'Teacher', 'Doctor'] },
    { emoji: '🦷', word: 'Dentist', wordHe: 'רופא שיניים', options: ['Doctor', 'Dentist', 'Nurse', 'Surgeon'] },
    { emoji: '🌻', word: 'Sunflower', wordHe: 'חמנייה', options: ['Rose', 'Sunflower', 'Daisy', 'Tulip'] },
    { emoji: '🦩', word: 'Flamingo', wordHe: 'פלמינגו', options: ['Flamingo', 'Pelican', 'Swan', 'Crane'] },
    { emoji: '🎹', word: 'Piano', wordHe: 'פסנתר', options: ['Guitar', 'Piano', 'Drum', 'Flute'] },
    { emoji: '⛵', word: 'Sailboat', wordHe: 'מפרשית', options: ['Sailboat', 'Canoe', 'Ship', 'Raft'] },
    { emoji: '🏕️', word: 'Camping', wordHe: 'קמפינג', options: ['Hiking', 'Camping', 'Fishing', 'Climbing'] },
    { emoji: '🎭', word: 'Comedy', wordHe: 'קומדיה', options: ['Drama', 'Comedy', 'Horror', 'Action'] },
  ],
  masters: [
    { emoji: '🧊', word: 'Break the ice', wordHe: 'לשבור את הקרח', options: ['Break the ice', 'Cold shoulder', 'On thin ice', 'Chill out'] },
    { emoji: '📖', word: 'Once upon a time', wordHe: 'היה היה פעם', options: ['Long time ago', 'Once upon a time', 'In the beginning', 'Way back when'] },
    { emoji: '🌧️', word: 'Under the weather', wordHe: 'לא מרגיש טוב', options: ['Under the weather', 'Raining cats', 'Storm coming', 'Cloudy mind'] },
    { emoji: '💡', word: 'Bright idea', wordHe: 'רעיון מבריק', options: ['Smart move', 'Bright idea', 'Light bulb', 'Quick thought'] },
    { emoji: '🍰', word: 'Piece of cake', wordHe: 'קל כמו משחק', options: ['Easy peasy', 'Piece of cake', 'Sweet deal', 'Cherry on top'] },
    { emoji: '⏰', word: 'Against the clock', wordHe: 'נגד השעון', options: ['Running late', 'Against the clock', 'Time flies', 'Clock ticking'] },
    { emoji: '🎭', word: 'Break a leg', wordHe: 'בהצלחה', options: ['Good luck', 'Break a leg', 'Take a bow', 'Steal the show'] },
    { emoji: '🌍', word: 'Small world', wordHe: 'עולם קטן', options: ['Small world', 'Big picture', 'Wide open', 'Close call'] },
    { emoji: '🔥', word: 'On fire', wordHe: 'בוער / מצוין', options: ['Burning up', 'On fire', 'Hot stuff', 'Fired up'] },
    { emoji: '🐘', word: 'Elephant in the room', wordHe: 'הפיל בחדר', options: ['Elephant in the room', 'Big deal', 'Heavy topic', 'Large problem'] },
    { emoji: '🐺', word: 'Cry wolf', wordHe: 'לזעוק זאב', options: ['Cry wolf', 'Bark loud', 'Howl long', 'Run wild'] },
    { emoji: '🌊', word: 'Go with the flow', wordHe: 'לזרום', options: ['Go with the flow', 'Swim upstream', 'Rock the boat', 'Make waves'] },
    { emoji: '🌙', word: 'Once in a blue moon', wordHe: 'פעם ביובל', options: ['Once in a blue moon', 'Every other day', 'Now and then', 'Time after time'] },
    { emoji: '🎯', word: 'Hit the nail on the head', wordHe: 'פגע בול', options: ['Hit the nail on the head', 'Miss the point', 'Close enough', 'Almost there'] },
    { emoji: '🐝', word: 'Busy as a bee', wordHe: 'עסוק כמו דבורה', options: ['Busy as a bee', 'Slow as a snail', 'Quiet as a mouse', 'Free as a bird'] },
    { emoji: '🌈', word: 'Every cloud has a silver lining', wordHe: 'אחרי הגשם בא השמש', options: ['Every cloud has a silver lining', 'Dark before dawn', 'Rainbow after rain', 'Sun will shine'] },
    { emoji: '🐱', word: 'Curiosity killed the cat', wordHe: 'סקרנות הרגה את החתול', options: ['Curiosity killed the cat', 'Cat got your tongue', 'Let the cat out', 'Copy cat'] },
    { emoji: '🎵', word: 'Face the music', wordHe: 'להתמודד עם התוצאות', options: ['Face the music', 'Play it cool', 'Change the tune', 'Sound the alarm'] },
    { emoji: '⚽', word: 'The ball is in your court', wordHe: 'הכדור במגרש שלך', options: ['The ball is in your court', 'Game over', 'Out of bounds', 'Fair play'] },
    { emoji: '🗝️', word: 'Under lock and key', wordHe: 'תחת מנעול', options: ['Under lock and key', 'Open door', 'Free access', 'Key to success'] },
    { emoji: '🌍', word: 'Think outside the box', wordHe: 'לחשוב מחוץ לקופסה', options: ['Think outside the box', 'Stay in line', 'Follow the rules', 'Keep it simple'] },
    { emoji: '🎪', word: 'Not my circus', wordHe: 'לא הקרקס שלי', options: ['Not my circus', 'My problem', 'In charge', 'Running the show'] },
  ],
};

export const SPELLING_CONTENT: Record<string, Array<{word: string, hint: string, hintHe: string}>> = {
  explorers: [
    { word: 'CAT', hint: '🐱 A furry pet', hintHe: '🐱 חיית מחמד רכה' },
    { word: 'DOG', hint: '🐶 Best friend', hintHe: '🐶 החבר הכי טוב' },
    { word: 'SUN', hint: '🌞 Bright in sky', hintHe: '🌞 בוהק בשמיים' },
    { word: 'BIG', hint: '📏 Not small', hintHe: '📏 לא קטן' },
    { word: 'RED', hint: '🔴 A color', hintHe: '🔴 צבע' },
    { word: 'HAT', hint: '🎩 On your head', hintHe: '🎩 על הראש' },
    { word: 'CUP', hint: '☕ Drink from it', hintHe: '☕ שותים ממנו' },
    { word: 'BUS', hint: '🚌 Big vehicle', hintHe: '🚌 רכב גדול' },
    { word: 'PEN', hint: '🖊️ Write with it', hintHe: '🖊️ כותבים איתו' },
    { word: 'BED', hint: '🛏️ Sleep in it', hintHe: '🛏️ ישנים בו' },
    { word: 'BOX', hint: '📦 Put things in', hintHe: '📦 שמים דברים בפנים' },
    { word: 'EGG', hint: '🥚 From chicken', hintHe: '🥚 מהתרנגולת' },
    { word: 'BAT', hint: '🦇 Flies at night', hintHe: '🦇 עף בלילה' },
    { word: 'COW', hint: '🐄 Gives milk', hintHe: '🐄 נותנת חלב' },
    { word: 'OWL', hint: '🦉 Night bird', hintHe: '🦉 ציפור לילה' },
    { word: 'ANT', hint: '🐜 Tiny worker', hintHe: '🐜 עובד קטנטן' },
    { word: 'PIE', hint: '🥧 Baked dessert', hintHe: '🥧 קינוח אפוי' },
    { word: 'HOT', hint: '🔥 Very warm', hintHe: '🔥 מאוד חם' },
    { word: 'FUN', hint: '🎉 Enjoyable', hintHe: '🎉 כיף' },
    { word: 'RUN', hint: '🏃 Move fast', hintHe: '🏃 לזוז מהר' },
    { word: 'MAP', hint: '🗺️ Shows places', hintHe: '🗺️ מראה מקומות' },
    { word: 'JAM', hint: '🍓 On bread', hintHe: '🍓 על הלחם' },
    { word: 'NET', hint: '🥅 Catch with it', hintHe: '🥅 תופסים איתו' },
    { word: 'MOP', hint: '🧹 Clean floor', hintHe: '🧹 מנקים רצפה' },
    { word: 'HUG', hint: '🤗 Warm embrace', hintHe: '🤗 חיבוק חם' },
    { word: 'ZIP', hint: '🤐 Close jacket', hintHe: '🤐 סוגרים מעיל' },
    { word: 'WET', hint: '💧 Not dry', hintHe: '💧 לא יבש' },
    { word: 'MUD', hint: '🟤 Dirty earth', hintHe: '🟤 אדמה מלוכלכת' },
    { word: 'GUM', hint: '🫧 Chew it', hintHe: '🫧 לועסים אותו' },
  ],
  voyagers: [
    { word: 'TIGER', hint: '🐅 Striped big cat', hintHe: '🐅 חתול גדול מפוספס' },
    { word: 'OCEAN', hint: '🌊 Vast blue water', hintHe: '🌊 מים כחולים עצומים' },
    { word: 'BRAVE', hint: '🦁 Not afraid', hintHe: '🦁 לא מפחד' },
    { word: 'DREAM', hint: '💭 While sleeping', hintHe: '💭 בזמן שינה' },
    { word: 'LIGHT', hint: '💡 Opposite of dark', hintHe: '💡 ההפך מחושך' },
    { word: 'WORLD', hint: '🌍 The whole planet', hintHe: '🌍 כל כדור הארץ' },
    { word: 'MUSIC', hint: '🎵 You listen to it', hintHe: '🎵 מקשיבים לזה' },
    { word: 'GREEN', hint: '🟢 Color of grass', hintHe: '🟢 צבע הדשא' },
    { word: 'HAPPY', hint: '😊 Feeling good', hintHe: '😊 מרגיש טוב' },
    { word: 'RIVER', hint: '🏞️ Flowing water', hintHe: '🏞️ מים זורמים' },
    { word: 'CLOUD', hint: '☁️ In the sky', hintHe: '☁️ בשמיים' },
    { word: 'BEACH', hint: '🏖️ Sand and sea', hintHe: '🏖️ חול וים' },
    { word: 'CANDY', hint: '🍬 Sweet treat', hintHe: '🍬 ממתק מתוק' },
    { word: 'CROWN', hint: '👑 King wears it', hintHe: '👑 המלך לובש את זה' },
    { word: 'PIZZA', hint: '🍕 Italian food', hintHe: '🍕 אוכל איטלקי' },
    { word: 'HORSE', hint: '🐴 You can ride it', hintHe: '🐴 אפשר לרכב עליו' },
    { word: 'WHALE', hint: '🐋 Biggest animal', hintHe: '🐋 החיה הכי גדולה' },
    { word: 'TRAIN', hint: '🚂 Rides on tracks', hintHe: '🚂 נוסע על מסילות' },
    { word: 'MAGIC', hint: '✨ Like a wizard', hintHe: '✨ כמו קוסם' },
    { word: 'DANCE', hint: '💃 Move to music', hintHe: '💃 לזוז למוזיקה' },
    { word: 'ROBOT', hint: '🤖 Machine person', hintHe: '🤖 אדם מכונה' },
    { word: 'SPACE', hint: '🚀 Beyond Earth', hintHe: '🚀 מעבר לכדור הארץ' },
    { word: 'HEART', hint: '❤️ Love symbol', hintHe: '❤️ סמל של אהבה' },
  ],
  masters: [
    { word: 'ADVENTURE', hint: '🗺️ Exciting journey', hintHe: '🗺️ מסע מרגש' },
    { word: 'BEAUTIFUL', hint: '🌸 Very pretty', hintHe: '🌸 מאוד יפה' },
    { word: 'KNOWLEDGE', hint: '📚 What you learn', hintHe: '📚 מה שלומדים' },
    { word: 'BRILLIANT', hint: '✨ Very smart', hintHe: '✨ מאוד חכם' },
    { word: 'CHALLENGE', hint: '🎯 A difficult task', hintHe: '🎯 משימה קשה' },
    { word: 'DANGEROUS', hint: '⚠️ Could be harmful', hintHe: '⚠️ יכול להיות מסוכן' },
    { word: 'EXCELLENT', hint: '🏆 Outstanding', hintHe: '🏆 מצוין' },
    { word: 'INVISIBLE', hint: '👻 Cannot be seen', hintHe: '👻 אי אפשר לראות' },
    { word: 'WONDERFUL', hint: '🌟 Amazing', hintHe: '🌟 מדהים' },
    { word: 'EDUCATION', hint: '🎓 Learning process', hintHe: '🎓 תהליך למידה' },
    { word: 'FANTASTIC', hint: '🤩 Incredibly good', hintHe: '🤩 טוב להפליא' },
    { word: 'NECESSARY', hint: '❗ Must have', hintHe: '❗ חייבים' },
    { word: 'SATELLITE', hint: '🛰️ Orbits Earth', hintHe: '🛰️ מקיף את כדור הארץ' },
    { word: 'VOLUNTEER', hint: '🤝 Help for free', hintHe: '🤝 עוזר בחינם' },
    { word: 'HURRICANE', hint: '🌀 Powerful storm', hintHe: '🌀 סופה חזקה' },
  ],
};

export const SENTENCE_CONTENT: Record<string, Array<{words: string[], correct: string, correctHe: string}>> = {
  explorers: [
    { words: ['I', 'like', 'cats'], correct: 'I like cats', correctHe: 'אני אוהב חתולים' },
    { words: ['The', 'sun', 'is', 'big'], correct: 'The sun is big', correctHe: 'השמש גדולה' },
    { words: ['She', 'has', 'a', 'dog'], correct: 'She has a dog', correctHe: 'יש לה כלב' },
    { words: ['I', 'can', 'run', 'fast'], correct: 'I can run fast', correctHe: 'אני יכול לרוץ מהר' },
    { words: ['The', 'bird', 'can', 'fly'], correct: 'The bird can fly', correctHe: 'הציפור יכולה לעוף' },
    { words: ['He', 'is', 'my', 'friend'], correct: 'He is my friend', correctHe: 'הוא החבר שלי' },
    { words: ['We', 'play', 'at', 'school'], correct: 'We play at school', correctHe: 'אנחנו משחקים בבית הספר' },
    { words: ['I', 'eat', 'an', 'apple'], correct: 'I eat an apple', correctHe: 'אני אוכל תפוח' },
    { words: ['The', 'cat', 'is', 'small'], correct: 'The cat is small', correctHe: 'החתול קטן' },
    { words: ['I', 'see', 'a', 'tree'], correct: 'I see a tree', correctHe: 'אני רואה עץ' },
    { words: ['She', 'likes', 'red', 'flowers'], correct: 'She likes red flowers', correctHe: 'היא אוהבת פרחים אדומים' },
    { words: ['We', 'love', 'ice', 'cream'], correct: 'We love ice cream', correctHe: 'אנחנו אוהבים גלידה' },
    { words: ['The', 'moon', 'is', 'bright'], correct: 'The moon is bright', correctHe: 'הירח בוהק' },
    { words: ['My', 'mom', 'is', 'nice'], correct: 'My mom is nice', correctHe: 'אמא שלי נחמדה' },
    { words: ['I', 'want', 'a', 'cookie'], correct: 'I want a cookie', correctHe: 'אני רוצה עוגייה' },
  ],
  voyagers: [
    { words: ['The', 'children', 'are', 'playing', 'outside'], correct: 'The children are playing outside', correctHe: 'הילדים משחקים בחוץ' },
    { words: ['She', 'always', 'reads', 'before', 'sleeping'], correct: 'She always reads before sleeping', correctHe: 'היא תמיד קוראת לפני השינה' },
    { words: ['We', 'went', 'to', 'the', 'beach'], correct: 'We went to the beach', correctHe: 'הלכנו לחוף' },
    { words: ['My', 'mother', 'cooks', 'delicious', 'food'], correct: 'My mother cooks delicious food', correctHe: 'אמא שלי מבשלת אוכל טעים' },
    { words: ['They', 'will', 'visit', 'us', 'tomorrow'], correct: 'They will visit us tomorrow', correctHe: 'הם יבקרו אותנו מחר' },
    { words: ['The', 'movie', 'was', 'really', 'exciting'], correct: 'The movie was really exciting', correctHe: 'הסרט היה ממש מרגש' },
    { words: ['I', 'have', 'been', 'studying', 'English'], correct: 'I have been studying English', correctHe: 'למדתי אנגלית' },
    { words: ['The', 'teacher', 'explained', 'the', 'lesson'], correct: 'The teacher explained the lesson', correctHe: 'המורה הסביר את השיעור' },
    { words: ['She', 'danced', 'in', 'the', 'rain'], correct: 'She danced in the rain', correctHe: 'היא רקדה בגשם' },
    { words: ['The', 'birds', 'sing', 'every', 'morning'], correct: 'The birds sing every morning', correctHe: 'הציפורים שרות כל בוקר' },
    { words: ['The', 'stars', 'shine', 'at', 'night'], correct: 'The stars shine at night', correctHe: 'הכוכבים זורחים בלילה' },
  ],
  masters: [
    { words: ['Despite', 'the', 'rain', 'they', 'continued', 'walking'], correct: 'Despite the rain they continued walking', correctHe: 'למרות הגשם הם המשיכו ללכת' },
    { words: ['She', 'would', 'have', 'arrived', 'earlier'], correct: 'She would have arrived earlier', correctHe: 'היא הייתה מגיעה מוקדם יותר' },
    { words: ['The', 'more', 'you', 'practice', 'the', 'better'], correct: 'The more you practice the better', correctHe: 'ככל שמתאמנים יותר כך משתפרים' },
    { words: ['If', 'I', 'had', 'known', 'I', 'would', 'have', 'helped'], correct: 'If I had known I would have helped', correctHe: 'אם הייתי יודע הייתי עוזר' },
    { words: ['Although', 'it', 'was', 'difficult', 'she', 'never', 'gave', 'up'], correct: 'Although it was difficult she never gave up', correctHe: 'למרות שזה היה קשה היא לא ויתרה' },
    { words: ['The', 'documentary', 'explored', 'ancient', 'civilizations'], correct: 'The documentary explored ancient civilizations', correctHe: 'הסרט התיעודי חקר תרבויות עתיקות' },
  ],
};

export const LISTENING_CONTENT: Record<string, Array<{word: string, wordHe: string, options: string[]}>> = {
  explorers: [
    { word: 'Hello', wordHe: 'שלום', options: ['Hello', 'Yellow', 'Jello', 'Fellow'] },
    { word: 'Apple', wordHe: 'תפוח', options: ['Apple', 'Ape', 'Able', 'April'] },
    { word: 'Water', wordHe: 'מים', options: ['Winter', 'Water', 'Waiter', 'Weather'] },
    { word: 'Happy', wordHe: 'שמח', options: ['Happy', 'Hippy', 'Hoppy', 'Handy'] },
    { word: 'Green', wordHe: 'ירוק', options: ['Grain', 'Green', 'Great', 'Greet'] },
    { word: 'House', wordHe: 'בית', options: ['Horse', 'House', 'Mouse', 'Hose'] },
    { word: 'Blue', wordHe: 'כחול', options: ['Blow', 'Blue', 'Blur', 'Blew'] },
    { word: 'Milk', wordHe: 'חלב', options: ['Milk', 'Silk', 'Mill', 'Melt'] },
    { word: 'Book', wordHe: 'ספר', options: ['Look', 'Book', 'Cook', 'Hook'] },
    { word: 'Ball', wordHe: 'כדור', options: ['Bell', 'Bill', 'Ball', 'Bull'] },
    { word: 'Rain', wordHe: 'גשם', options: ['Rain', 'Run', 'Ruin', 'Ran'] },
    { word: 'Tree', wordHe: 'עץ', options: ['Free', 'Tree', 'Three', 'Thee'] },
    { word: 'Fish', wordHe: 'דג', options: ['Dish', 'Fish', 'Wish', 'Fist'] },
    { word: 'Snow', wordHe: 'שלג', options: ['Show', 'Snow', 'Slow', 'Know'] },
    { word: 'Cake', wordHe: 'עוגה', options: ['Cape', 'Cake', 'Lake', 'Make'] },
    { word: 'Play', wordHe: 'לשחק', options: ['Pray', 'Play', 'Clay', 'Slay'] },
  ],
  voyagers: [
    { word: 'Beautiful', wordHe: 'יפה', options: ['Beautiful', 'Bountiful', 'Botanical', 'Butterfly'] },
    { word: 'Chocolate', wordHe: 'שוקולד', options: ['Challenge', 'Chocolate', 'Champion', 'Character'] },
    { word: 'Important', wordHe: 'חשוב', options: ['Impatient', 'Impossible', 'Important', 'Immediate'] },
    { word: 'Vegetable', wordHe: 'ירק', options: ['Vegetable', 'Variable', 'Valuable', 'Vulnerable'] },
    { word: 'Wonderful', wordHe: 'נפלא', options: ['Wanderful', 'Wonderful', 'Waterfall', 'Worthwhile'] },
    { word: 'Different', wordHe: 'שונה', options: ['Difficult', 'Different', 'Diligent', 'Diplomat'] },
    { word: 'Dangerous', wordHe: 'מסוכן', options: ['Dangerous', 'Generous', 'Glamorous', 'Delicious'] },
    { word: 'Celebrate', wordHe: 'לחגוג', options: ['Celebrate', 'Calibrate', 'Calculate', 'Cultivate'] },
    { word: 'Butterfly', wordHe: 'פרפר', options: ['Butterfly', 'Buttercup', 'Beautiful', 'Battleship'] },
    { word: 'Education', wordHe: 'חינוך', options: ['Elevation', 'Education', 'Equation', 'Evolution'] },
    { word: 'Dinosaur', wordHe: 'דינוזאור', options: ['Dinosaur', 'Dilemma', 'Discover', 'Diamond'] },
    { word: 'Lemonade', wordHe: 'לימונדה', options: ['Lemonade', 'Limousine', 'Landscape', 'Longitude'] },
  ],
  masters: [
    { word: 'Phenomenon', wordHe: 'תופעה', options: ['Phenomenon', 'Philosophy', 'Philanthropy', 'Photography'] },
    { word: 'Sophisticated', wordHe: 'מתוחכם', options: ['Sophisticated', 'Sympathetic', 'Supplementary', 'Surveillance'] },
    { word: 'Extraordinary', wordHe: 'יוצא דופן', options: ['Extravagant', 'Extraordinary', 'Experimental', 'Exaggerated'] },
    { word: 'Pronunciation', wordHe: 'הגייה', options: ['Proclamation', 'Pronunciation', 'Predominant', 'Professional'] },
    { word: 'Encyclopedia', wordHe: 'אנציקלופדיה', options: ['Encyclopedia', 'Enthusiastic', 'Environmental', 'Entrepreneurial'] },
    { word: 'Architecture', wordHe: 'אדריכלות', options: ['Architecture', 'Archaeology', 'Aristocracy', 'Articulation'] },
    { word: 'Determination', wordHe: 'נחישות', options: ['Determination', 'Deterioration', 'Documentation', 'Denomination'] },
    { word: 'Simultaneously', wordHe: 'בו זמנית', options: ['Simultaneously', 'Systematically', 'Spontaneously', 'Substantially'] },
  ],
};